
apiVersion: apps/v1
kind: Deployment
metadata:
  name: help-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: help-center
  template:
    metadata:
      labels:
        app: help-center
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: help-center
          image: 834283091445.dkr.ecr.ap-south-1.amazonaws.com/help-center:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-app-key
                  key: APP_KEY
            - name: SESSION_DRIVER
              value: "file"
---
apiVersion: v1
kind: Service
metadata:
  name: help-center-service
spec:
  type: NodePort
  selector:
    app: help-center
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
